[package]
name = "steam-totp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.11.0"
sha-1 = "0.9.8"
byteorder = "1"
base64 = "0.13.0"